### ISSUE TITLE
Provide original source code

### ISSUE THREAD

**Issue by XVincentX** [TrackJs/trackjs-package#11]
Sometimes you want to look into `trackjs` source code directly to understand what's going on.

With the actual state, it's minified and mangled - therefore it's boring and time consuming.

**Comment by BrandesEric** [comment]
We've gone back and forth over open sourcing the tracker JavaScript (or, even displaying the original source under a less permissive license), but it's not something we've officially committed to at this time.  For now we would rather have people treat the script as a black box. (We do realize that it's not terribly hard to reverse engineer for someone committed to the task.)

In any event, we are very committed to supporting the script and ensuring it does not cause issues.  So, if you're having problems with the script we'd love to know about them, and help work through them with you!

**Comment by Almad** [comment]
@BrandesEric This is a bit of bummer for us. Could you please explain more?

From a business perspective, if there are tricks that help you track errors significantly better than alternatives, it's worth spending time to deminify and port, so I don't see much reason there, but would be interested in hearing otherwise.

From s security perspective, I certainly hope there is nothing that's security by obscurity.

From our security perspective, you are asking us to run a black box script in the context of our page, which totally sounds like a big risk. Also, as `track.js` potentially has access to customer data, trust is a big issue anyway—and asking us to "just trust it"™ and complicating potential audit, you are not sending the right signal.

Additionally, it complicates integration issues quite a bit, which is not really encouraging.

**Comment by toddhgardner** [comment]
Hi @Almad et al. 

Our tracker script does quite a few things better than alternatives in the marketplace. Our source is verbose with comments explaining browser quirks and why certain behaviors exist to be as exhaustive as possible in capturing the best error information. 

From a business perspective, we consider our tracker script a competitive advantage. Over 3 years in, and no one has matched its capabilities yet. We know of several attempts to reverse-engineer our code, and they have all been naive in their interpretations and missed many subtle bugs. Revealing our documented source publicly would make it immediately copied into other tools and destroy some of our uniqueness.

We totally understand your security concerns. It is uncomfortable to introduce third-party script onto your page unless you know exactly what it does. It is somewhat concerning to me that this has become standard practice for many SaaS companies.

For this reason, we do provide a security review for potential business customers to see the source and speak with our team on implications to privacy and risks. If you are interested in this, please contact us over email and we'll set it up. hello@trackjs.com.

We are web developers ourselves and spend time integrating our service into other tools and JavaScript libs. If you're interested in doing that, we'd love to work with you to make it great.

TrackJS is a small, bootstrapped company. Developing, testing, and growing these capabilities and quirks came at personal cost and time from our team. We're trying to strike the right balance of transparency while not giving away the core things that make us valuable.

**Comment by Almad** [comment]
@toddhgardner I can understand that concern, and I think it's valid; I haven't been doing that deep-dive of the comparisons. I still don't like it, but I understand it :) 

With that, do you think it would be possible to have limited access under NDA? I think what we are after is an access to source code during integration experience. Private npm with source code for those who sign, and public one for deploymens?

I'll reach out to the mentioned email, and let's talk there.
