### ISSUE TITLE
'tracker.d.ts' is not a module error

### ISSUE THREAD

**Issue by hisham** [TrackJs/trackjs-package#14]
I'm trying to use trackJs in Angular 2 with typescript / angular-cli, and am getting this error during the webpack bundling: 

`File '.../node_modules/trackjs/tracker.d.ts' is not a module.`

I am importing trackjs as follows: 

`import { trackJs } from 'trackjs/tracker';`

Any help? I'm relatively new to typescript...

**Comment by BrandesEric** [comment]
Hi Hisham, due to the way our script was originally written for a browser environment, you cannot import it quite like that.  Take a look at this example code repo for our typical webpack approach: https://github.com/TrackJs/js-integrations/tree/master/webpack-and-npm

Once you've set up the `exports-loader` you should be able to do

`import trackJs from 'trackJs'`  (Note the omission of the { curly brackets }, we're essentially exporting "default" in this case)

Let me know how it goes!

**Comment by hisham** [comment]
I see. angular-cli doesn't allow specifying webpack config directly. However, they seem to have their own config for this case - see https://github.com/angular/angular-cli#global-library-installation. 

So I added the `../node_modules/trackjs/tracker.js` script in angular-cli.json under `scripts`. That resolved the webpack error. 

But intelliJ still didn't have auto complete for trackjs. It gave a file not found in tsconfig.json error or similar. So I added '../node_modules/trackjs' under 'typeRoots' in tsconfig.json. Now intelliJ got the autocomplete and was recognizing trackJs. 

I also couldn't do: 

`import trackJs from 'trackJs'`

That would cause webpack error, so what I did instead is: 

`import 'trackjs/tracker';`

Not sure if last step was needed but now there are no errors, auto complete works, and trackjs is working too. 

You can close this if you wish.

**Comment by BrandesEric** [comment]
Hey Hisham, `import 'trackjs/tracker';` will work great in this case!
