### ISSUE TITLE
TypeScript error: "tracker.d.ts is not a module"

### ISSUE THREAD

**Issue by iFadey** [TrackJs/trackjs-package#23]
When import is used in typescript code
`import { trackJs } from 'trackjs';`

I am getting this error:
`File '.../node_modules/trackjs/tracker.d.ts' is not a module`

**Comment by toddhgardner** [comment]
Hi @iFadey, thanks for reaching out. This doesn't work because the tracking agent is not a module--the nature of how our tracking works fundamentally manipulates the global namespaces. We highly recommend loading the tracker as the *first* script on the page, so that we can capture errors during initialization.

The TypeScript definitions describe how you can interact with our API, but we are not a module.
