### ISSUE TITLE
trackjs console intercept causes DevTools to label all output as coming from your code

### ISSUE THREAD

**Issue by bytenik** [TrackJs/trackjs-package#28]
When TrackJS is included in our code, all console output appears to come from `tracker.js:13` in DevTools. This makes it difficult to figure out where a problem might be and diagnose it via debugging, because there's nothing tying an output back to its generating lines of code.

**Comment by BrandesEric** [comment]
Hi @bytenik,

This is a consequence of the low-level console wrapping we do.  We give a few tips in [our docs](https://docs.trackjs.com/tracker/tips#developing-locally) of some things you can do to make developing locally easier.   TrackJS is really meant for production and prod-like environments where the errors are affecting non-developer users, and you need that context about what happened, but don't have access to the dev tools console.   So lots of times folks will just disable TrackJS locally, or blackbox the script.  

If you really don't want to ever watch the console, you can turn the wrapping off completely, even when the agent is enabled, by adding the following configuration:
```
window._trackJs = {
  console:  {
    enabled: false 
  }
}
```

Hope that helps!  

Thanks!
Eric

**Comment by bytenik** [comment]
It seems as though even when the agent is disabled, console logs are still wrapped. And unfortunately you cannot black box scripts that are bundled together: https://bugs.chromium.org/p/chromium/issues/detail?id=583193

It appears that merely by having the script imported, it is affecting the global scope by wrapping console.

**Comment by toddhgardner** [comment]
Hey @bytenik! Thanks for bringing this up.

If you set `_trackJs.enabled = false`, the agent will not interact with `window.console` at all, and you should not see us in your dev console. This setting enables/disables everything the agent does.

If you set `_trackJs.console.enabled = false`, it will also not interact with `window.console`, but all other parts (like network and visitor tracking) will continue to work.

Please note that these settings can only be set once, as once the `tracker` script has loaded it has already read the settings from the `_trackJs` configuration.

So for your local development, I recommend that you disable the console wrapping so that you still get error reports and mirror the rest of the production Api.

Please let me know if there is anything else I can help with.

**Comment by bytenik** [comment]
Unfortunately, that isn't possible. Imports are hoisted in JS and will run before executable code such as setting enabled to false.

**Comment by toddhgardner** [comment]
@bytenik Understood. We are working on making the tracker into a normal module to give you better behavior in this situation.

In the meantime, I believe you can make a module called `trackJsConfig` that creates the `_trackJs` configuration object with how you want it to be. Then, you can import your config before the tracker to get this control.

**Comment by toddhgardner** [comment]
TrackJS is now a module as of agent v3.0.0, currently in canary testing. You can reference it as a module from npm:

`npm install trackjs@canary`

```javascript
import { TrackJS } from 'trackjs';
TrackJS.install({ token: 'YOUR_TOKEN' });
```
