### ISSUE TITLE
Issue with google web master

### ISSUE THREAD

**Issue by pkumar01** [TrackJs/trackjs-package#35]
Hi,

I am using trackJs with my production application and after multiple hit and trial came to know that track js is blocking my page rendering with google webmaster so now i delayed the script loading and it worked fine for now but i know this is not the solution can u you please help me how to handle this case.

I am using reactJs 16.3 and i am loading my js inside didmount.

Thanks,
Pradeep

**Comment by toddhgardner** [comment]
Hi @pkumar01, thanks for reaching out! We recommend placing the agent script as the first script on your page, and block other scripts from loading, so that we are able to capture errors during initialization. By loading the script asynchronously, you can miss loading and startup errors from other scripts that load before we do.

The best way to solve this is to bring in the agent as a npm dependency and bundle it into your application. [Here is some information on how to do that](https://docs.trackjs.com/browser-agent/installation/#bundling-as-a-module).

[And some further information on React.](https://docs.trackjs.com/browser-agent/integrations/react-redux/)

Let me know if you need something more!
