### ISSUE TITLE
invalid escape sequence with copied code from website

### ISSUE THREAD

**Issue by pkbarbiedoll** [TrackJs/trackjs-package#44]
After including this snippet in my page header (between the <head></head> tags)

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JX6YMC6L6X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JX6YMC6L6X');
</script>
<script data-consolejs-channel="16aca95e-4af3-a026-5531-f988d20c73f8" src="https://remotejs.com/agent/agent.js"></script>

```

I show this in https://remotejs.com/viewer/16aca95e-4af3-a026-5531-f988d20c73f8 

```
Invalid escape sequence

value@https://remotejs.com/agent/agent.js:14:119320
value@https://remotejs.com/agent/agent.js:14:119447
value@https://remotejs.com/agent/agent.js:14:120198
A@https://remotejs.com/agent/agent.js:14:116061
e.cloneWindow@https://remotejs.com/agent/agent.js:14:124216
A/<@https://remotejs.com/agent/agent.js:14:30109

```

Not sure what to do to resolve.

**Comment by BrandesEric** [comment]
@pkbarbiedoll Hi, it looks like RemoteJS is capturing an error that is pre-existing on your page.  
 
I get the following same error in the console of the browser when visiting the site.
![image](https://github.com/TrackJs/trackjs-package/assets/640877/ce8b30c6-71a2-43cc-ac4a-01dc4268c4fa)

Coming from here:
![image](https://github.com/TrackJs/trackjs-package/assets/640877/f623f18a-566d-4fea-ae24-17f489433308)

Which is this code
```js
function MM_preloadImages() { //v3.0
	var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
        var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
	if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
```

Which is in turn called in the `onLoad` of this element:

```html
<body bgcolor=070707 style='background:#070707' text=white leftmargin=0 topmargin=0 onLoad=\"MM_preloadImages('images/layout4e_on_01.jpg','images/layout4e_on_03.jpg','images/layout4e_on_05.jpg','images/layout4e_on_06.jpg','images/layout4e_on_07.jpg','images/layout4e_on_08.jpg','images/layout4e_on_10.jpg','images/layout4e_on_11.jpg')\">
```

Which indeed DOES have a bad escape sequence (the `onLoad` attribute should be `onLoad=""` instead of `onLoad=\"\"`)

So anyways, this is just an error that RemoteJS is surfacing to you - but the stack trace is sorta funky because it's not occurring inside a script file - but rather in HTML.

**Comment by BrandesEric** [comment]
Closing as not related to RemoteJS.
