### ISSUE TITLE
Allow initialisation without a token

### ISSUE THREAD

**Issue by ninjatronic** [TrackJs/trackjs-package#5]
Since [you already provide a way for it to be configured post-initialisation](http://docs.trackjs.com/JavaScript_Api_Reference/trackJs.configure/token) please also provide a way to initialise the library without a token.

**Use Case:**

My build script ([Ember CLI](http://www.ember-cli.com/)) concatenates all my `bower_components` into a single file. I wish to configure the token at runtime depending on environment variables etc. My index.html is clean and I don't want to paste a snippet in there to preconfigure a token.

The error I get originates from [here](https://gist.github.com/statico/6495bb88816a423d1be1#file-track-js-L653).

**Comment by toddhgardner** [comment]
Thanks for the detailed explanation @ninjatronic. I am not super familiar with EmberCLI, but would it be possible to have a `bower_components_config` that you put vendor configuration like ours into and use your build to inject it before the `bower_components`?

**Comment by ninjatronic** [comment]
@toddhgardner yes technically this would be possible, but it's still a very non standard solution. A better way would be to allow the SDK to be loaded via the script tag and then initialised in code after load.

Polluting `window` with a `_trackjs` object doesn't seem very clean, nor does using a tag on the script. Most integration libraries like this follow the load _then_ configure pattern, rather than configure _then_ load.

**Comment by jherdman** [comment]
@ninjatronic in the event you haven't resolved your problem yet, you may want to consider using my ember-cli TrackJS package that works around a few funny edge cases when bootstrapping TrackJS: http://emberobserver.com/addons/ember-cli-trackjs.

If you have some functionality in your wrapper that I'm missing, I'm more than receptive to pull requests!

**Comment by karellm** [comment]
@toddhgardner It looks like most errors in this repo are actually the same. It's been 5 months, can we expect a fix? Those are really simple problem to fix. 

And TrackJs is the only library I tried (airbrake and honeybadger) requiring this, so it is definitely possible to remove the need for the `_trackJs` object.

**Comment by BrandesEric** [comment]
@karellm Unfortunately the fix is not so simple :(  If you supply a token after page load; after other scripts have initialized, you run the risk of missing errors that were thrown by those scripts. We find that page initialization is a very common place for errors to occur.

That being said, I do think it would be nice to allow you to configure a token after other scripts initialize, but we'd need to be queuing any errors that occur before you configure a token, so you don't miss anything.  We'd then need to send them in batch after token was provided.  It's definitely doable but not something we can just get done in a few hours.  We've had a few other really high priorities over the last few months, but I do know we're planning some upgrades to the tracker in the near future.  I'll suggest this as a new feature!

**Comment by karellm** [comment]
@BrandesEric Makes total sense. Thanks for taking the time to explain!

**Comment by toddhgardner** [comment]
We have rearranged things in agent v3.0.0, currently in canary testing. You can now reference the script separate from installing it in your page. 

```html
<script src="https//cdn.trackjs.com/agent/v3/canary/t.js></script>"
<script>
  TrackJS.install({ token: 'your-token' });
</script>
```

You still have the issue where errors that occur before TrackJS has been installed would not be recorded, but this should give you the flexibility you are looking for.
